# Generated by Django 5.0.1 on 2024-03-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_employee_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
