# Generated by Django 5.0.1 on 2024-03-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_employer_user_remove_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'Ph.D.'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
