# Generated by Django 5.0.1 on 2024-03-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_subscriptionplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
