# Generated by Django 5.0.1 on 2024-03-08 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_employee_employer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='JobSeeker',
        ),
    ]
