# Generated by Django 5.0.1 on 2024-03-22 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_company_jobseeker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Employer',
        ),
    ]
