# Generated by Django 5.0.1 on 2024-03-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_alter_employer_user_alter_jobseeker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
