# Generated by Django 5.0.1 on 2024-03-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0028_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
